name: Create release

on:
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.0.0

      - name: Determine tag name
        id: generate_tag
        run: |
          # 現在の日付を取得
          date_prefix=$(date +"%Y.%m.%d")
          n=1

          # 同じ日付のタグを確認し、存在する場合はインクリメント
          while git rev-parse -q --verify "refs/tags/$date_prefix.$n" >/dev/null; do
            n=$((n+1))
          done

          echo "tag_name=$date_prefix.$n" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          gh release create ${{ steps.generate_tag.outputs.tag_name }} --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
