name: Create release

on:
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.0.0

      - name: Determine tag name
        id: generate_tag
        run: |
          # 現在の日付を取得
          date_prefix=$(date +"%Y.%m.%d")
          n=1

          # 同じ日付のタグが存在するか確認
          existing_tags=$(gh release list --limit 100 --json tagName -q '.[] | .tagName' | grep "^${date_prefix}")

          # タグのインクリメント処理
          while echo "$existing_tags" | grep -q "^${date_prefix}\.${n}$"; do
            n=$((n+1))
          done

          echo "tag_name=$date_prefix.$n" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          gh release create ${{ steps.generate_tag.outputs.tag_name }} --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
